<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\API\BaseController as BaseController;
use App\Models\User;
use App\Models\Technician;
use Illuminate\Support\Facades\Auth;
use Validator;
use Illuminate\Support\Facades\Hash;
use App\Rules\MatchOldPassword;
use App\Http\Resources\UserProfileCollection;

class UserController extends BaseController
{
    public function userProfile($user_id=null){
        try
        {
            $user_details = auth()->user();
            if($user_details) {
                return $this->sendResponse('PROFILE GET SUCCESSFULLY', new UserProfileCollection($user_details));
            } else {
                return $this->sendError('UNAUTHORIZE ACCESS', 200); 
            }
        }
        catch (\Throwable $e)
        {
            return $this->sendError($e->getMessage().' on line '.$e->getLine(), 400);  
        }   
    }

    public function changePassword(Request $request){
        $error_message =    [
            'current_password.required'    => 'Current Password should be required',
            'new_password.required'    => 'New Password should be required',
        ];
        $rules = [
            'current_password' => ['required', new MatchOldPassword],
            'new_password'         => 'required',            
        ];
        $validator = Validator::make($request->all(), $rules, $error_message);   
        if($validator->fails()){
            return $this->sendError($validator->errors()->all(), 200);       
        } 
        try
        {
            $user_details = auth()->user();
            if($user_details) {
                \DB::beginTransaction();
                $change = User::find(auth()->user()->id)->update(['password'=> Hash::make($request->new_password)]);
                \DB::commit();
                return $this->sendResponse('Password change succssfully');
            } else {
                return $this->sendError('UNAUTHORIZE ACCESS', 200); 
            }
        }
        catch (\Throwable $e)
        {
            \DB::rollback();
            return $this->sendError($e->getMessage().' on line '.$e->getLine(), 400);  
        } 
    }

    function changePassword2(Request $request) {
     $data = $request->all();
     $user = auth()->user();

     //Changing the password only if is different of null
     if( isset($data['oldPassword']) && !empty($data['oldPassword']) && $data['oldPassword'] !== "" && $data['oldPassword'] !=='undefined') {
         //checking the old password first
         $check =  auth()->attempt(['mobile' => $user->mobile, 'password' => $request->old_password]);         
         if($check && isset($data['new_password']) && !empty($data['new_password']) && $data['newPassword'] !== "" && $data['newPassword'] !=='undefined') {
             $user->password = bcrypt($data['newPassword']);
             $user->isFirstTime = false; //variable created by me to know if is the dummy password or generated by user.
             $user->token()->revoke();
             $token = $user->createToken('newToken')->accessToken;

             //Changing the type
             $user->save();

             return json_encode(array('token' => $token)); //sending the new token
         }
         else {
             return "Wrong password information";
         }
     }
     return "Wrong password information";
 }

}
